server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
